spring:
  application:
    name: my-duck-store
  datasource:
    url: jdbc:postgresql://localhost:5432/duckstore
    username: postgres
    password: Probuddy
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: info