package com.myduckstore.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.tags.Tag;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

/**
 * Customises the OpenAPI document generated by springdoc.
 *
 * <p>The Swagger UI is available at {@code /swagger-ui.html}.
 * The raw OpenAPI 3 spec (JSON) is at {@code /v3/api-docs}.
 */
@Configuration
public class OpenApiConfig {

    @Bean
    public OpenAPI duckStoreOpenAPI() {
        return new OpenAPI()
                .info(new Info()
                        .title("My Duck Store API")
                        .version("1.0.0")
                        .description("""
                                REST API for the **Duck Warehouse** (stock management) \
                                and the **Duck Store** (order pricing).

                                * **Warehouse** — create, list, edit and logically delete ducks.
                                * **Store** — price a potential order; no stock is consumed.
                                """)
                        .contact(new Contact()
                                .name("My Duck Store")))
                .tags(List.of(
                        new Tag().name("Warehouse")
                                 .description("Duck stock management — CRUD operations on the warehouse inventory"),
                        new Tag().name("Store")
                                 .description("Order pricing — compute a quote without reserving or consuming stock")
                ));
    }
}
